### ISSUE TITLE
Issue with text between to tags

### ISSUE THREAD

**Issue by tomikais** [d1vanov/basic-xml-syntax-highlighter#1]
Hi d1vanov,

first, nice work! I like your XML syntax highlighter.

I found an issue in your current version. When you have text between to tags and the text contains space character the formatting isn't correct.

E.g.: 
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<body>Dont forget me this weekend!</body>

![snap1](https://cloud.githubusercontent.com/assets/7860085/9081815/e1c9ab90-3b5f-11e5-8e66-00985f05dd00.jpg)

Formatting "Dont forget me this weekend!" isn't correct. 

Best regards
Thomas

**Comment by d1vanov** [comment]
Hi tomikais,

Thank you very much for reporting this, I applied some regex magic to fix the issue, pushed the result to master. Should work ok now, please check it.

**Comment by d1vanov** [comment]
Found one more problem with highlighting for xml elements consisting of a single symbol e.g. <b>, fixed, pushed to master as well.

**Comment by tomikais** [comment]
Naice work!
