### ISSUE TITLE
Issue with a dot

### ISSUE THREAD

**Issue by tiga05** [d1vanov/basic-xml-syntax-highlighter#2]
Hello,

I think I found a possible bug in your nice tool. 

Using a dot within the square brack removes the highlighting for this line.

Example: 
`<field value="."/> `
or just 
`<field . />`

leads to:

![image](https://user-images.githubusercontent.com/1228542/69704850-9c62b280-10f4-11ea-9fbe-b91f89819569.png)

**Comment by d1vanov** [comment]
Hi there!

Example
```
<field value="."/>
```
seems to work for me:
![example_019](https://user-images.githubusercontent.com/2050562/69729248-08fea100-1137-11ea-8a75-e6e944adad0e.png)
Example
```
<field . />
```
also seems to work:
![example -2-‎_020](https://user-images.githubusercontent.com/2050562/69729638-b96ca500-1137-11ea-9213-c38d8b68741c.png)

It seems your issue with highlighting is caused by something else. Could you please attach minimal complete xml file on which the problem reproduces?

**Comment by tiga05** [comment]
Hello again,

I created a basic application.
[testApp.zip](https://github.com/d1vanov/basic-xml-syntax-highlighter/files/3900564/testApp.zip)

This application created exactly this result:
![image](https://user-images.githubusercontent.com/1228542/69788346-9afdbc80-11be-11ea-9c27-aea936d65a65.png)

But if there is a space between the tag and the dot, it works again. And it looks like that nearly all symbols are affected. f.e : !?"§$,%& and so on....

Normally I use Visual Studio. The highlighting in VS-App does not work independent of the number of spaces. But only the dot is affected. Other symbols seems to work.

I am using QT 5.9.2 and Windows 10.

Looks like you also have the bug in your example. Just have a look at your first line in your screenshots. The utf-8 is black instead of highlighted, because the question marker is directly behind the end of the quote. Add a space and then it should be colorized

**Comment by tiga05** [comment]
If you are able to open Visual Studio projects, try this: 

[QtGuiApplication1.zip](https://github.com/d1vanov/basic-xml-syntax-highlighter/files/3900710/QtGuiApplication1.zip)

Result of an example string in VS:
`<attribute type="text" key1="posNumber" key2="" value="2"/>`
`<attribute type="longtext" key1="content" key2="de" value="someTEXT .\n"/>`

![image](https://user-images.githubusercontent.com/1228542/69791370-afdd4e80-11c4-11ea-86c8-121e89f5ef17.png)

(because of the dot in "value", the attribute tag is not highlighted anymore)

**Comment by d1vanov** [comment]
Ok, I think I figured what it is and got it fixed. Please update and try again.

**Comment by tiga05** [comment]
Yep it works now. The weird Visual Studio behavior was my fault. My example does not use your original code.

Thank you!

**Comment by d1vanov** [comment]
Great, glad it works now. Thanks for reporting it!

**Comment by tiga05** [comment]
Unfortunately, it looks like the changes had a side effect. 😞 

Text between two tags is now highlighted. example:
`<message> THIS CONTENT SHOULD NOT BE HIGHLIGHTED </message>`
result:
![image](https://user-images.githubusercontent.com/1228542/69808778-a6fe7400-11e8-11ea-8ba6-f603ba290f2f.png)

**Comment by d1vanov** [comment]
Yeah, I see... I'll try to find some way to correct it.

**Comment by d1vanov** [comment]
Pushed one more attempt to fix it, please give it a try.

**Comment by tiga05** [comment]
https://github.com/d1vanov/basic-xml-syntax-highlighter/blob/e113cc540360e79cdfbc42572d1b7deac67009bd/basic-xml-syntax-highlighter/BasicXMLSyntaxHighlighter.cpp#L66

Add a ">" at the end of the regex and I think then you are done 👍 .
` m_xmlElementRegex.setPattern("<[?\\s]*[/]?[\\s]*([^\\n][^>]*)(?=[\\s/>])>"); `



This prevents a not highlighted closing bracket:
![image](https://user-images.githubusercontent.com/1228542/69852548-d793eb80-1284-11ea-8a3a-a05659265a70.png)


![image](https://user-images.githubusercontent.com/1228542/69852413-7c61f900-1284-11ea-90d8-f7d4bf096a69.png)

But please double check it. I am not a regex expert.

**Comment by d1vanov** [comment]
Strange, it works for me with the current regex...
![example_021](https://user-images.githubusercontent.com/2050562/69872286-0da58f80-12c6-11ea-9415-9402d5c2505d.png)

Are you sure you rebuilt the code after updating?
The thing is, the ending `>` you added is already present in the lookahead expression just before it: `(?=[\\s/>])`. This says "look ahead for either whitespace character or / or >".

**Comment by tiga05** [comment]
Yes you are right. I tried it with my PC at home and everything is working here.

I think everything is fixed now.

Thanks for your great work!

**Comment by d1vanov** [comment]
Great, thanks for testing my fix attempts! :smiley:
